[versions]

debug-panel = "0.9.3"
flipper = "2.0.1"
gradle-infrastructure = "0.19.1"
inputmask = "7.2.6"
itemsadapter = "1.1"
konfeature = "0.1.0"
ktx-core = "1.6.0-2"
ktx-fragment = "1.3.6-0"
ktx-fragment-args = "1.3.6-1"
ktx-livedata = "2.3.1-0"
ktx-resources = "1.3.1-0"
ktx-viewbinding = "4.2.1-0"
mapmemory = "2.1"
pinkman = "1.3.2"
textvalue = "1.0.2"

[libraries]

debug-panel-accounts = { module = "com.redmadrobot.debug:plugin-accounts", version.ref = "debug-panel" }
debug-panel-core = { module = "com.redmadrobot.debug:panel-core", version.ref = "debug-panel" }
debug-panel-konfeature = { module = "com.redmadrobot.debug:plugin-konfeature", version.ref = "debug-panel" }
debug-panel-noop = { module = "com.redmadrobot.debug:panel-no-op", version.ref = "debug-panel" }
debug-panel-servers = { module = "com.redmadrobot.debug:plugin-servers", version.ref = "debug-panel" }
flipper = { module = "com.redmadrobot:flipper", version.ref = "flipper" }
flipper-firebaseConfig = { module = "com.redmadrobot:flipper-firebase-config", version.ref = "flipper" }
infrastructure-android = { module = "com.redmadrobot.build:infrastructure-android", version.ref = "gradle-infrastructure" }
infrastructure-detekt = { module = "com.redmadrobot.build:infrastructure-detekt", version.ref = "gradle-infrastructure" }
infrastructure-kotlin = { module = "com.redmadrobot.build:infrastructure-kotlin", version.ref = "gradle-infrastructure" }
infrastructure-publish = { module = "com.redmadrobot.build:infrastructure-publish", version.ref = "gradle-infrastructure" }
inputmask = { module = "com.redmadrobot:input-mask-android", version.ref = "inputmask" }
itemsadapter = { module = "com.redmadrobot.itemsadapter:itemsadapter", version.ref = "itemsadapter" }
itemsadapter-viewbinding = { module = "com.redmadrobot.itemsadapter:itemsadapter-viewbinding", version.ref = "itemsadapter" }
konfeature = { module = "com.redmadrobot.konfeature:konfeature", version.ref = "konfeature" }
ktx-core = { module = "com.redmadrobot.extensions:core-ktx", version.ref = "ktx-core" }
ktx-fragment = { module = "com.redmadrobot.extensions:fragment-ktx", version.ref = "ktx-fragment" }
ktx-fragment-args = { module = "com.redmadrobot.extensions:fragment-args-ktx", version.ref = "ktx-fragment-args" }
ktx-livedata = { module = "com.redmadrobot.extensions:lifecycle-livedata-ktx", version.ref = "ktx-livedata" }
ktx-resources = { module = "com.redmadrobot.extensions:resources-ktx", version.ref = "ktx-resources" }
ktx-viewbinding = { module = "com.redmadrobot.extensions:viewbinding-ktx", version.ref = "ktx-viewbinding" }
mapmemory = { module = "com.redmadrobot.mapmemory:mapmemory", version.ref = "mapmemory" }
mapmemory-coroutines = { module = "com.redmadrobot.mapmemory:mapmemory-coroutines", version.ref = "mapmemory" }
mapmemory-kaptBugWorkaround = { module = "com.redmadrobot.mapmemory:mapmemory-kapt-bug-workaround", version.ref = "mapmemory" }
mapmemory-rxjava2 = { module = "com.redmadrobot.mapmemory:mapmemory-rxjava2", version.ref = "mapmemory" }
mapmemory-rxjava3 = { module = "com.redmadrobot.mapmemory:mapmemory-rxjava3", version.ref = "mapmemory" }
mapmemory-test = { module = "com.redmadrobot.mapmemory:mapmemory-test", version.ref = "mapmemory" }
pinkman = { module = "com.redmadrobot:pinkman", version.ref = "pinkman" }
pinkman-coroutines = { module = "com.redmadrobot:pinkman-coroutines", version.ref = "pinkman" }
pinkman-rx3 = { module = "com.redmadrobot:pinkman-rx3", version.ref = "pinkman" }
pinkman-ui = { module = "com.redmadrobot:pinkman-ui", version.ref = "pinkman" }
textvalue = { module = "com.redmadrobot.textvalue:textvalue", version.ref = "textvalue" }
textvalue-compose = { module = "com.redmadrobot.textvalue:textvalue-compose", version.ref = "textvalue" }

[plugins]

android-application = { id = "com.redmadrobot.application", version.ref = "gradle-infrastructure" }
android-config = { id = "com.redmadrobot.android-config", version.ref = "gradle-infrastructure" }
android-library = { id = "com.redmadrobot.android-library", version.ref = "gradle-infrastructure" }
detekt = { id = "com.redmadrobot.detekt", version.ref = "gradle-infrastructure" }
kotlin-config = { id = "com.redmadrobot.kotlin-config", version.ref = "gradle-infrastructure" }
kotlin-library = { id = "com.redmadrobot.kotlin-library", version.ref = "gradle-infrastructure" }
publish = { id = "com.redmadrobot.publish", version.ref = "gradle-infrastructure" }
publish-config = { id = "com.redmadrobot.publish-config", version.ref = "gradle-infrastructure" }
